export const HOME__GET_FILTERS_SUCCESS = "HOME__GET_FILTERS_SUCCESS";
export const HOME__GET_FILTERS_ERROR = "HOME__GET_FILTERS_ERROR";
export const FILTER_PANEL__CHANGE_FILTER_SELECTION = "FILTER_PANEL__CHANGE_FILTER_SELECTION";
export const FILTER_PANEL__UPDATE_FILTER_SELECTION = "FILTER_PANEL__UPDATE_FILTER_SELECTION";
export const FILTER_PANEL__FILTER_SELECT_ALL = "FILTER_PANEL__FILTER_SELECT_ALL";
export const FILTER_PANEL__FILTER_UNSELECT_ALL = "FILTER_PANEL__FILTER_UNSELECT_ALL";

export const FILTER__EXPAND = "FILTER__EXPAND";
export const FILTER__COLLAPSE = "FILTER__COLLAPSE";

export const SIDEBAR__SHOW = "SIDEBAR__SHOW";
export const SIDEBAR__HIDE = "SIDEBAR__HIDE";
